os: linux
dist: bionic
language: csharp
solution: mvp/mvp.sln
dotnet: 5.0.103
mono: none
install: dotnet restore mvp/mvp.sln
before_install:
- openssl aes-256-cbc -K $encrypted_56635d5d55b3_key -iv $encrypted_56635d5d55b3_iv
  -in do_ssh_key.enc -out ssh_keys/do_ssh_key -d
- chmod 600 /tmp/git_deploy_key
- echo 'echo ${SSH_PASSPHRASE}' > /tmp/askpass && chmod +x /tmp/askpass
- eval "$(ssh-agent -s)"
- DISPLAY=":0.0" SSH_ASKPASS="/tmp/askpass" setsid ssh-add /tmp/git_deploy_key </dev/null
stages:
- test
- deploy
jobs:
  include:
  - stage: test
    name: run pytest
    install: skip
    script:
    - cd mvp/
    - dotnet test
  - stage: deploy
    name: deploy new version
    install: skip
    script: |
      ssh -o "StrictHostKeyChecking no" ${MT_USER}@${DB_SERVER} \
      "cd /vagrant  && \
      git clone https://github.com/LVOL98/E-vil-Corp && \
      cd mvp/DB && \
      dotnet run && \
      exit"
      ssh -o "StrictHostKeyChecking no" ${MT_USER}@{WEB_SERVER} \
      "cd /vagrant && \
       git clone https://github.com/LVOL98/E-vil-Corp && \
       cd mvp/server && \
       dotnet run && \
       exit"
