name: CI/CD

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

####

  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy: 
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
      
    
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'
          
      - name: Install dependencies
        run: dotnet restore mvp/
          
      - name: Build with dotnet 
        run: dotnet build mvp/ --configuration Release
      
      - name: Run tests
        run: dotnet test mvp/ --configuration Release
  
  
  ####
  
  deploy:
    needs: build-and-test # make sure we build and test before we actually deploy 
    
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v1 # checks from main branch
      
      - name: Copy file via scp
        uses: appleboy/scp-action@master # for copying the repo to remote host on digitalocean
        env:
          HOST: ${{secrets.SSH_DB_IP}} # droplet public ip (stored in secrets)
          USERNAME: ${{ secrets.SSH_DB_USERNAME }} # droplet username (root for now)
          KEY: ${{secrets.SSH_DB_KEY}} # private ssh key generated on remote host 
        with:
          source: "." # this repo
          target: "repo/" # copies the repo to the test folder on remote machine 
    
      - name: Execute minitwit on droplet
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.SSH_DB_IP}} # ip addres of the server
          key: ${{secrets.SSH_DB_KEY}}
          username: ${{ secrets.SSH_DB_USERNAME }}
          
          script: |
            cd test/
            fuser -k -n tcp 5010
            sleep 4s
            fuser -k -n tcp 5000
            sleep 4s
            nohup dotnet run --project mvp/DB > foo.out 2> foo.err < /dev/null &
            sleep 15s
            nohup dotnet run --project mvp/server >> foo.out 2>> foo.err < /dev/null &
            sleep 10s
            cat foo.out
