# This is a basic workflow to help you get started with Actions

name: Report Update

on:
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the latest version of the master branch
      - uses: actions/checkout@v2

      - name: Sync changes with 
        run: |
          echo Hello World!
          echo Report\ Latex/main.tex
