# This is a basic workflow to help you get started with Actions

name: Report Update

on:
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the latest version of the master branch
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

      - name: Setup of Latex compiler and compile pdf
        uses: xu-cheng/latex-action@v2
        with:
          root_file: report/main.tex
      
      # - name: Upload main.pdf as artifact
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: PDF
      #     path: main.pdf
      
      - name: Move and rename pdf into correct folder
        run: |
          ls
          rm -f report/build/Group-E-report.pdf
          mkdir -p report/build/
          mv main.pdf report/build/Group-E-report.pdf
      
      - name: Commit files
        run: |
          git add report/build/Group-E-report.pdf
          git commit -m "Upload pdf to correct folder"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}

#       - name: Download pdf from artifacts
#         uses: actions/download-artifact@v2
#         with:
#           name: PDF
#           path: report/build/
 
#       - name: Check folder
#         run: | 
#           ls -R
#           ls
#         working-directory: report/build/
      
#       - name: Download artifact
#         uses: dawidd6/action-download-artifact@v2
#         with:
#           # Required, workflow file name or ID
#           workflow: report-overleaf.yml
#           # Optional, directory where to extract artifact
#           path: report/build/
