# This is a basic workflow to help you get started with Actions

name: Report Update

on:
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the latest version of the master branch
        uses: actions/checkout@v2

      - name: Setup of Latex compiler and compile pdf
        uses: xu-cheng/latex-action@v2
        with:
          root_file: report/main.tex
      
      - name: Upload main.pdf as artifact
        uses: actions/upload-artifact@v2
        with:
          name: PDF
          path: report/build/main.pdf

      - name: Check folder
        run: |
          cd /report
          ls